services:
  - type: web
    name: Token-find
    env: ruby
    buildCommand: bundle install && bundle exec rake assets:precompile
    startCommand: bundle exec rails server -b 0.0.0.0
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MAX_THREADS
        value: '5'
      - key: FIND_THE_TOKEN_DATABASE_PASSWORD
        value: t4PMcTSBaFVwwrqwB3zHkfwyUrDTzRob
      - key: SECRET_KEY_BASE
        value: 617a63e850ef9f609e2aa5e22159343be515fd4c3c6d7513e4a30070826efa56c8a5adde7607d386edcb326a12c3fc0f4042c9cdcf1a9e603c9792f8215289a7

databases:
  - name: game2
    engine: postgres
    connectionString: postgres://game2_user:t4PMcTSBaFVwwrqwB3zHkfwyUrDTzRob@dpg-cgriq2e4dad30thuoebg-a/game2

jobs:
  - type: periodic
    name: run-migrations
    env: ruby
    cronSpec: '@hourly'
    buildCommand: bundle install
    runCommand: bundle exec rake db:migrate
    envVars:
      - key: DATABASE_URL
        value: postgres://game2_user:t4PMcTSBaFVwwrqwB3zHkfwyUrDTzRob@dpg-cgriq2e4dad30thuoebg-a/game2
