services:
  - type: web
    name: Token find
    env: ruby
    buildCommand: "bundle install && yarn install && bundle exec rails assets:precompile"
    runCommand: "bundle exec rails db:migrate && bundle exec rails server -p 5000 -b 0.0.0.0"
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        fromEnvVar: DATABASE_URL
      - key: SECRET_KEY_BASE
        fromEnvVar: SECRET_KEY_BASE