services:
  - type: web
    name: my-rails-app
    env: ruby
    buildCommand: "bundle install && yarn install && bundle exec rails assets:precompile"
    runCommand: "bundle exec rails db:migrate && bundle exec rails server -p 5000 -b 0.0.0.0"
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        value: your_database_url
      - key: SECRET_KEY_BASE
        value: your_secret_key_base
